/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorPanel: typeof import('./src/components/ColorPanel.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker.vue')['default']
    ConfigPanel: typeof import('./src/components/ConfigPanel.vue')['default']
    Copy: typeof import('./src/components/Copy.vue')['default']
    Download: typeof import('./src/components/Download.vue')['default']
    HistoryPanel: typeof import('./src/components/HistoryPanel.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    MathJaxPreview: typeof import('./src/components/MathJaxPreview.vue')['default']
    MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
    OpacityPicker: typeof import('./src/components/OpacityPicker.vue')['default']
    Painter: typeof import('./src/components/Painter.vue')['default']
    Resizable: typeof import('./src/components/Resizable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SavePanel: typeof import('./src/components/SavePanel.vue')['default']
    Tabbar: typeof import('./src/components/Tabbar.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
  }
}
